# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
            ],
            options={
                'verbose_name': 'online issue',
                'verbose_name_plural': 'online issues',
            },
        ),
        migrations.CreateModel(
            name='PrintIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'print issue',
                'verbose_name_plural': 'print issues',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='online_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.OnlineIssue'),
        ),
        migrations.AddField(
            model_name='article',
            name='print_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.PrintIssue'),
        ),
    ]
