# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170212_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printissue',
            name='title',
        ),
        migrations.AddField(
            model_name='printissue',
            name='issue',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printissue',
            name='volume',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
