# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170212_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineissue',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printissue',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
