# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170212_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blurb',
            field=models.TextField(default='This is the blurb.'),
            preserve_default=False,
        ),
    ]
