# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_bio',
            field=models.TextField(default='The author of the article.', verbose_name='author biography'),
            preserve_default=False,
        ),
    ]
