# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symposiumpage',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symposiumpage',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
