# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposia', '0002_auto_20170216_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symposiumpage',
            options={'ordering': ['-volume']},
        ),
        migrations.RemoveField(
            model_name='symposiumpage',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='symposiumpage',
            name='parent',
        ),
        migrations.AddField(
            model_name='symposiumpage',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symposiumpage',
            name='reg_link',
            field=models.URLField(blank=True, null=True, verbose_name='Registration Link'),
        ),
        migrations.AddField(
            model_name='symposiumpage',
            name='volume',
            field=models.PositiveSmallIntegerField(default=94),
            preserve_default=False,
        ),
    ]
