# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposia', '0003_auto_20170220_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symposiumpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
